### ISSUE TITLE
missing menu sass files

### ISSUE THREAD

**Issue by Ross-Rawlins** [johannesjo/angular-material-sass-files#2]
on your new release you are missing the menu sass files.

**Comment by johannesjo** [comment]
Which files exactly do you mean?

**Comment by Ross-Rawlins** [comment]
menu.scss and menu-bar where missing from the bower install and they where not included in the angular-material import file.

**Comment by johannesjo** [comment]
It should work now. I forgot to release a new bower version.

**Comment by Ross-Rawlins** [comment]
ok cool but I just ran it and there are stiill missing files and the styles seem off
