### ISSUE TITLE
(bug)Button scss

### ISSUE THREAD

**Issue by kasselTrankos** [johannesjo/angular-material-sass-files#3]
Is a great idea, but i think will be over time from original angular material wich includes .scss but for all, not for every component as you done.

The bug is in the button scss, when it is pressed.
tks

**Comment by johannesjo** [comment]
Thanks for reporting, but could you elaborate? Is it a bug which only happens with this repo?

**Comment by kasselTrankos** [comment]
yes, you can see this using this commit.
https://github.com/kasselTrankos/angular-webpack-tdd/commit/60c218214019f42f7b30f0499299bc68e72f202c
as you make it run, when you click under buttons, then you can see what happens.
I solved using original .scss from angular material, i dont change nothing as you see in this other commit
https://github.com/kasselTrankos/angular-webpack-tdd/commit/7e67e59343a59b50d76d55e0cc7fdc401d216129
tks

**Comment by kasselTrankos** [comment]
hi, im trying to make work, and i seen is needed _struture.scs,  an then i put, but the ripple animation not work s fine, will give any idea of which
i,ve created a branch in the point at give you
https://github.com/kasselTrankos/angular-webpack-tdd/tree/old-state
the ripple container not work as is expected. Could you take a look
tks
Afeter search what is happening, i thin the problem is the ripple effect, doesnt wrk propertly,

**Comment by kasselTrankos** [comment]
Founded what is happening, 
Im using bower so the version as default installed is 0.8.3, and not 1.0.0.
So the command to bower is
 bower i -S angular-material-sass-files#v1.0.0-rc1
please put that info in your readme.md
tks

**Comment by johannesjo** [comment]
Thanks for reporting. I added a hint in the readme and also updated the package to the latest version.
