### ISSUE TITLE
Release 1.0.5 on Bower

### ISSUE THREAD

**Issue by gregoriokusowski** [johannesjo/angular-material-sass-files#4]
Hi there.

```
$ bower info angular-material-sass-files
```

Returns only `0.8.3` as available version.

Are there plans for new releases on bower? Would be nice to have them, otherwise I think we can change the Readme to avoid old installs. WDYT?

**Comment by johannesjo** [comment]
Should be available now. Thanks for reporting!

**Comment by gregoriokusowski** [comment]
Thanks!
